#!/usr/bin/env python3
"""Generate an I/O-bound wrapper around a Dynamatic-exported kernel.

    python3 hw/dyn_wrap.py <exported_top.v> <kernel_name> > dyn_top.v

A kernel this size has far more ports than the part has pins, so it cannot be
routed as a top level and its period cannot be measured.  The wrapper's whole
job is to get the port count down to three without landing on any path that
belongs to the kernel: every input comes off a register, every output is
XOR-reduced into a register.  The period nextpnr then reports for clk is the
kernel's own.

The port list is READ FROM THE EXPORTED FILE rather than written down here.
The first version of this hardcoded xorshift's ports and silently described
only that one kernel -- pointed at collatz it failed loudly, which was lucky;
pointed at a kernel that happened to share port names it would have failed
quietly, which is the case worth designing against.
"""
import re
import sys

PORT = re.compile(r"(input|output)\s*(?:wire\s*)?(?:\[\s*(\d+)\s*:\s*(\d+)\s*\])?\s*(\w+)")


def main():
    path, kernel = sys.argv[1], sys.argv[2]
    src = open(path).read()
    m = re.search(r"\bmodule\s+" + re.escape(kernel) + r"\s*\((.*?)\)\s*;",
                  src, re.S)
    if not m:
        sys.exit(f"no module {kernel} in {path}")
    ins, outs = [], []
    for d, hi, lo, name in PORT.findall(m.group(1)):
        # re returns '' (not None) for an unmatched optional group.
        w = int(hi) - int(lo) + 1 if hi else 1
        (ins if d == "input" else outs).append((name, w))

    # clk and rst are ours to drive, not part of the handshake surface.
    ins = [(n, w) for n, w in ins if n not in ("clk", "rst")]

    o = []
    e = o.append
    e("// GENERATED by hw/dyn_wrap.py -- do not edit.  See that file for why")
    e("// this wrapper exists and why its ports are read rather than written.")
    e("`default_nettype none")
    e("module dyn_top (input wire clk_p, output wire led_red, output wire led_green);")
    e("  wire clk;")
    e("  BUFG bg (.I(clk_p), .O(clk));")
    e("  reg [7:0] boot = 8'h0;")
    e("  reg rst = 1'b1;")
    e("  always @(posedge clk) begin boot <= boot + 8'h1; rst <= (boot < 8'h10); end")
    e("")
    # Wide inputs get their own LFSR so the kernel sees changing operands and
    # nothing constant-folds away; one-bit inputs (the valids and readys) come
    # off boot bits, which keeps them toggling without a critical path.
    for i, (n, w) in enumerate(ins):
        if w > 1:
            e(f"  reg [{w-1}:0] r_{n} = {w}'d{(i + 1) * 0x9E37};")
            e(f"  always @(posedge clk) r_{n} <= {{r_{n}[{w-2}:0], "
              f"r_{n}[{w-1}] ^ r_{n}[{max(w-11, 0)}]}};")
        else:
            e(f"  reg r_{n} = 1'b0;")
            e(f"  always @(posedge clk) r_{n} <= boot[{i % 8}];")
    e("")
    for n, w in outs:
        e(f"  wire {'[%d:0] ' % (w-1) if w > 1 else ''}o_{n};")
    e("")
    e(f"  {kernel} dut (")
    conn = [".clk(clk)", ".rst(rst)"]
    conn += [f".{n}(r_{n})" for n, _ in ins]
    conn += [f".{n}(o_{n})" for n, _ in outs]
    e("    " + ",\n    ".join(conn) + ");")
    e("")
    # Every output must reach a register or synthesis prunes the logic behind
    # it and the period would describe a kernel with holes in it.
    half = (len(outs) + 1) // 2
    for k, grp in enumerate((outs[:half], outs[half:])):
        terms = " ^ ".join(f"(^o_{n})" for n, _ in grp) or "1'b0"
        e(f"  reg acc{k} = 1'b0;")
        e(f"  always @(posedge clk) acc{k} <= {terms};")
    e("  assign led_red   = acc0;")
    e("  assign led_green = acc1;")
    e("endmodule")
    e("`default_nettype wire")
    print("\n".join(o))


if __name__ == "__main__":
    main()
