#!/usr/bin/env bash
# iCE40 flow for async (clockless) bundled-data designs:
#   run_flow.sh <design.v> <top> <outdir>
# Produces <outdir>/<top>.asc and <outdir>/<top>.bin plus a sanity report,
# with the deliberate combinational feedback structures verified intact.
# See boards/ice40/README.md for the full story.
set -euo pipefail

if [ $# -ne 3 ]; then
  echo "usage: $0 <design.v> <top> <outdir>" >&2
  exit 2
fi

DESIGN="$(readlink -f "$1")"
TOP="$2"
OUTDIR="$(mkdir -p "$3" && readlink -f "$3")"

BOARD_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(readlink -f "$BOARD_DIR/../..")"
RTL="$ROOT/rtl"

# Tool locations (override via env if needed).
YOSYS="${YOSYS:-$HOME/dev2/lib/fpgatoolchain/yosys/build/yosys}"
NEXTPNR="${NEXTPNR:-$HOME/dev2/lib/fpgatoolchain/nextpnr/build/nextpnr-ice40}"
ICEPACK="${ICEPACK:-$HOME/dev2/lib/fpgatoolchain/icestorm/icepack/icepack}"

# Device: iCE40UP5K, sg48 (largest UP5K package). nextpnr reports 39 usable
# SB_IO sites for it; designs with more port bits than that get an IO shim
# (see step 1). Smoke flow only -- the bitstream never touches hardware.
DEVICE_FLAG="--up5k"
PACKAGE="sg48"
IO_BUDGET="${ICE40_IO_BUDGET:-39}"

echo "== ice40 flow: design=$DESIGN top=$TOP outdir=$OUTDIR"

# ---------------------------------------------------------------------------
# Step 1: probe the top-level ports. UP5K has at most 39 IO pads but hlsc
# designs can have wide channel ports (addmul: 69 port bits). nextpnr
# auto-creates one SB_IO per port bit, so wide designs cannot place. Since
# this bitstream never leaves the workstation, we graft a zero-logic IO shim:
# scalar ports pass through, every wide input is driven by one shared pin
# `si` replicated, every wide output exposes only bit 0. The shim is grafted
# AFTER synth_ice40 with a plain flatten, so no opt pass can const-propagate
# through the shared/replicated nets into the datapath (verified: SB_LUT4
# count is identical with and without the shim).
# ---------------------------------------------------------------------------
# (probe uses `portlist`, not write_json: the cells_sim.v lib modules contain
# processes that this yosys's JSON backend refuses to export.)
"$YOSYS" -q -p "
  read_verilog -lib +/ice40/cells_sim.v;
  read_verilog -DSYNTHESIS -sv -I $RTL $RTL/async.sv;
  read_verilog -DSYNTHESIS -sv -I $RTL $DESIGN;
  hierarchy -top $TOP;
  tee -o $OUTDIR/ports.txt portlist $TOP"

NEED_SHIM=$(python3 - "$OUTDIR/ports.txt" "$TOP" "$IO_BUDGET" "$OUTDIR/shim.v" <<'PYEOF'
import re, sys
probe, top, budget, shim_path = sys.argv[1], sys.argv[2], int(sys.argv[3]), sys.argv[4]
ports = []  # (name, width, direction)
for line in open(probe):
    m = re.match(r"\s*(input|output|inout)\s+\[(\d+):(\d+)\]\s+(\S+)", line)
    if m:
        d, hi, lo, name = m.group(1), int(m.group(2)), int(m.group(3)), m.group(4)
        ports.append((name, abs(hi - lo) + 1, d))
total_bits = sum(w for _, w, _ in ports)
if total_bits <= budget:
    print(f"port bits = {total_bits} <= IO budget {budget}: no shim", file=sys.stderr)
    print("no")
    sys.exit(0)
scalars, wide_in, wide_out = [], [], []
for name, w, d in ports:
    if d == "inout":
        sys.exit(f"inout port {name}: not supported by the IO shim")
    (scalars if w == 1 else wide_in if d == "input" else wide_out).append((name, w, d))
pins = 1 + len(scalars) + len(wide_out)  # si + scalars + one b0 pin per wide output
if pins > budget:
    sys.exit(f"even the IO shim needs {pins} pins > budget {budget}")
lines = ["// Auto-generated by run_flow.sh: zero-logic IO shim so the design",
         "// fits UP5K pads. Grafted after synthesis; adds no cells.",
         "module ice40_smoke_shim ("]
decls = ["  input si"] + [f"  {p[2]} {p[0]}" for p in scalars] \
      + [f"  output {p[0]}_b0" for p in wide_out]
lines.append(",\n".join(decls) + ");")
for n, w, _ in wide_out:
    lines.append(f"  wire [{w-1}:0] {n};")
conns = [f".{n}({n})" for n, _, _ in scalars]
conns += [f".{n}({{{w}{{si}}}})" for n, w, _ in wide_in]
conns += [f".{n}({n})" for n, w, _ in wide_out]
lines.append(f"  {top} core ({', '.join(conns)});")
for n, _, _ in wide_out:
    lines.append(f"  assign {n}_b0 = {n}[0];")
lines.append("endmodule")
open(shim_path, "w").write("\n".join(lines) + "\n")
print(f"port bits = {total_bits} > IO budget {budget}: shim with {pins} pins",
      file=sys.stderr)
print("yes")
PYEOF
)
echo "== IO shim: $NEED_SHIM"

# ---------------------------------------------------------------------------
# Step 2: compose synth.gen.ys from the template and run yosys.
# ---------------------------------------------------------------------------
JSON="$OUTDIR/$TOP.json"
if [ "$NEED_SHIM" = "yes" ]; then
  SHIM_SECTION="# IO shim graft: read + flatten only, AFTER all optimization, so nothing\n\
# can const-propagate through the shared shim nets into the datapath.\n\
read_verilog -sv $OUTDIR/shim.v\n\
hierarchy -top ice40_smoke_shim\n\
flatten\n\
tee -o $OUTDIR/shim.stat stat\n"
else
  SHIM_SECTION="# (no IO shim needed: ports fit the package)\n"
fi

sed -e "s|@RTL_DIR@|$RTL|g" \
    -e "s|@DESIGN@|$DESIGN|g" \
    -e "s|@TOP@|$TOP|g" \
    -e "s|@OUTDIR@|$OUTDIR|g" \
    -e "s|@BOARD_DIR@|$BOARD_DIR|g" \
    -e "s|@JSON@|$JSON|g" \
    -e "s|@SHIM_SECTION@|$SHIM_SECTION|g" \
    "$BOARD_DIR/synth.ys" > "$OUTDIR/synth.gen.ys"

echo "== yosys"
"$YOSYS" -q -l "$OUTDIR/yosys.log" -s "$OUTDIR/synth.gen.ys"

# ---------------------------------------------------------------------------
# Step 3: place and route. --ignore-loops is REQUIRED: the netlist is full of
# intentional combinational loops and nextpnr's timing-graph construction
# would otherwise abort. No --force or other special flags are needed. No
# .pcf on purpose: IO is auto-placed (this bitstream never touches hardware).
# nextpnr's timing/Fmax output is meaningless for clockless logic -- ignore
# it (custom signoff via the nextpnr Python API per-cell delay hooks is a
# separate milestone).
# ---------------------------------------------------------------------------
echo "== nextpnr-ice40 $DEVICE_FLAG --package $PACKAGE --ignore-loops"
# --sdf: routed per-cell IOPATH + per-connection INTERCONNECT delays, the
# data source for the timing signoff step below.
"$NEXTPNR" $DEVICE_FLAG --package "$PACKAGE" --ignore-loops \
  --json "$JSON" --asc "$OUTDIR/$TOP.asc" --sdf "$OUTDIR/$TOP.sdf" \
  -l "$OUTDIR/nextpnr.log" -q

echo "== icepack"
"$ICEPACK" "$OUTDIR/$TOP.asc" "$OUTDIR/$TOP.bin"

# ---------------------------------------------------------------------------
# Step 4: sanity checks + report.
# ---------------------------------------------------------------------------
TIMING_JSON="${DESIGN%.v}.timing.json"
python3 - "$OUTDIR" "$TOP" "$NEED_SHIM" "$TIMING_JSON" <<'PYEOF'
import json, os, re, sys

outdir, top, shim, timing_path = sys.argv[1], sys.argv[2], sys.argv[3] == "yes", sys.argv[4]
fails, notes = [], []

def counts(stat_file):
    c = {}
    for line in open(stat_file):
        m = re.match(r"\s*(\d+)\s+(\S+)\s*$", line)
        if m:
            c[m.group(2)] = c.get(m.group(2), 0) + int(m.group(1))
    return c

core = counts(f"{outdir}/core.stat")
final = counts(f"{outdir}/final.stat")
mid = counts(f"{outdir}/shim.stat") if shim else None

lb = core.get("loop_breaker", 0)
lut_core, lut_final = core.get("SB_LUT4", 0), final.get("SB_LUT4", 0)
carry_core, carry_final = core.get("SB_CARRY", 0), final.get("SB_CARRY", 0)

# 1. loop_breaker bookkeeping: every library lut has exactly 5 breakers.
if lb == 0 or lb % 5 != 0:
    fails.append(f"loop_breaker count {lb} is not a positive multiple of 5")
lib_luts = lb // 5
datapath_luts = lut_core - lib_luts

# 2. dissolution must not change SB_LUT4/SB_CARRY counts, and no breaker may
#    survive into the JSON.
if mid is not None and (mid.get("SB_LUT4") != lut_core or mid.get("loop_breaker") != lb):
    fails.append(f"shim graft changed counts: {mid}")
if lut_final != lut_core:
    fails.append(f"SB_LUT4 changed across dissolution: {lut_core} -> {lut_final}")
if carry_final != carry_core:
    fails.append(f"SB_CARRY changed across dissolution: {carry_core} -> {carry_final}")
if final.get("loop_breaker", 0) != 0:
    fails.append(f"{final['loop_breaker']} loop_breaker cells survived dissolution")

# 3. yosys must never have seen (let alone broken) the feedback loops.
ylog = open(f"{outdir}/yosys.log").read()
for m in re.finditer(r"Found (\d+) SCCs", ylog):
    if int(m.group(1)) != 0:
        fails.append(f"yosys detected combinational loops: '{m.group(0)}'")
# abc9 always *defines* a $__ABC9_SCC_BREAKER helper module; that is benign
# boilerplate as long as no cell of that type is ever instantiated (checked
# against final.stat below).
bad_lines = [l for l in ylog.splitlines()
             if re.search(r"break", l, re.I) and "loop_breaker" not in l
             and "breaker" not in l
             and not l.startswith("Generating RTLIL representation")]
if bad_lines:
    fails.append("suspicious 'break' lines in yosys.log: " + "; ".join(bad_lines[:5]))
scc_cells = [t for t in final if "SCC_BREAKER" in t.upper()]
if scc_cells:
    fails.append(f"abc9 SCC breaker cells in final netlist: {scc_cells}")
# 'Removed N cells' during coarse synth is datapath $-cell lowering (normal);
# the count invariants above prove no library cell was eaten.
removed = re.findall(r"Removed a total of (\d+) cells", ylog)
notes.append(f"opt cell removals during datapath lowering: {removed} "
             "(datapath $-cells only; library counts proven intact above)")

# 4. rough consistency vs the compiler's timing sidecar. The M3 backend
#    renamed "stages" to "elements" (hlatch + merge_delay kinds); the exact
#    per-element structure (every mullerc, latch bit, and delay LUT located
#    by name) is verified by the timing-signoff step, which is strictly
#    stronger than the old M2 shape formula.
if os.path.exists(timing_path):
    t = json.load(open(timing_path))
    elems = t.get("elements", t.get("stages", []))
    sum_t = sum(s["T"] for s in elems)
    if sum_t > lib_luts:
        fails.append(f"delay-chain LUTs (sum T={sum_t}) exceed library LUTs {lib_luts}")
    else:
        notes.append(f"sidecar: {len(elems)} timing elements, sum T={sum_t} "
                     f"delay LUTs <= {lib_luts} library LUTs (exact structural "
                     "check done by the signoff step)")
else:
    notes.append(f"no timing sidecar at {timing_path}; skipped consistency check")

# 5. nextpnr / icepack results.
plog = open(f"{outdir}/nextpnr.log").read()
if "Routing complete" not in plog or "Program finished normally" not in plog:
    fails.append("nextpnr did not finish routing cleanly")
if re.search(r"^ERROR", plog, re.M):
    fails.append("ERROR lines in nextpnr.log")
util = {m.group(1): (int(m.group(2)), int(m.group(3)))
        for m in re.finditer(r"(\S+):\s+(\d+)/\s*(\d+)\s+\d+%", plog)}
bin_path = f"{outdir}/{top}.bin"
if not (os.path.exists(bin_path) and os.path.getsize(bin_path) > 0):
    fails.append("missing/empty .bin")

lc = util.get("ICESTORM_LC", ("?", "?"))
io = util.get("SB_IO", ("?", "?"))
report = f"""iCE40 async flow sanity report
==============================
design top          : {top}   (IO shim: {"yes" if shim else "no"})
SB_LUT4 pre-PnR     : {lut_core}  = {lib_luts} library (loop_breaker/5) + {datapath_luts} datapath
SB_CARRY (datapath) : {carry_core}
loop_breaker pre    : {lb}   (= 5 x {lib_luts} library LUTs)
loop_breaker post   : {final.get("loop_breaker", 0)}
SB_LUT4 post-dissolve: {lut_final} (unchanged: {"yes" if lut_final == lut_core else "NO"})
ICESTORM_LC placed  : {lc[0]}/{lc[1]}   (post-PnR; = SB_LUT4 + carry-packing LCs)
SB_IO placed        : {io[0]}/{io[1]}
notes:
""" + "".join(f"  - {n}\n" for n in notes)
report += "result: " + ("FAIL\n" + "".join(f"  ! {f}\n" for f in fails) if fails else "PASS\n")
open(f"{outdir}/sanity_report.txt", "w").write(report)
print(report)
sys.exit(1 if fails else 0)
PYEOF

# ---------------------------------------------------------------------------
# Step 5: bundled-data timing signoff (gate). Verifies, per consuming
# element, that the routed request path is slower than every routed datapath
# it covers (tools/timing_signoff.py; data source: nextpnr's SDF). A design
# that fails signoff is not a deliverable. Gate policy (Q9): per comparison
# slack >= max(0.2 x data, 200 ps); SIGNOFF_POLICY=zero for the plain >= 0
# debug gate.
# ---------------------------------------------------------------------------
if [ -f "$TIMING_JSON" ]; then
  echo "== timing signoff"
  python3 "$ROOT/tools/timing_signoff.py" \
    --sdf "$OUTDIR/$TOP.sdf" --sidecar "$TIMING_JSON" \
    --policy "${SIGNOFF_POLICY:-ratio}" \
    --report "$OUTDIR/signoff_report.txt"
else
  echo "== WARNING: no timing sidecar at $TIMING_JSON -- SIGNOFF SKIPPED" >&2
fi

echo "== done: $OUTDIR/$TOP.bin"
