#!/usr/bin/env python3
"""Emit cmpsweep.vh: drive ucmpi11's operand directly and read its answer.

The one test that separates a mis-synthesised comparator from a comparator
that is fine but was sampled during startup.  Everything observed so far is
consistent with both: in the gcd run the only three transactions that ever
carry a negative operand are the FIRST three, and all three come out wrong --
after which the loop is poisoned and every later sample is positive, so the
run contains no steady-state evidence at all.

So stop waiting for the design to produce operands and supply them.  `force`
overrides the latch driving each bit of the comparator's a_data, holds it long
enough for the cone to settle by any reasonable margin, and reads the cell's
own result net.  No handshake, no startup, no sampling edge to get wrong -- if
the answers are right here, the cone is right and the fault is in when the
design presents its operands; if they are wrong here, the cone is wrong and no
amount of delay anywhere will fix it.

The forces are released afterwards, and the sweep runs late enough that reset
is long done.
"""
import json, os, re, sys

HERE = os.environ.get("GLS_WORK") or os.path.dirname(os.path.abspath(__file__))
top = json.load(open(os.path.join(HERE, "routed.json")))["modules"]["top"]
nets = top["netnames"]

# The comparator's a_data has no net of its own under that name: it IS the
# probe port, so the routed netlist calls it rig_cmp_in.  Same wire, and the
# one the cell actually reads.
A, Z = "rig_cmp_in", "rig_cmp_z"

idx = {}
for n, nn in nets.items():
    m = re.fullmatch(re.escape(A) + r"\[(\d+)\]", n)
    if m and len(nn["bits"]) == 1 and isinstance(nn["bits"][0], int):
        idx[int(m.group(1))] = nn["bits"][0]
if not idx:
    sys.exit(f"gen_cmpsweep: no operand net {A}")
w = max(idx) + 1
if any(k not in idx for k in range(w)):
    sys.exit(f"gen_cmpsweep: {A} missing bits")
zb = nets[Z]["bits"][0]

TESTS = [-6, -9, -3, -1, 0, 1, 6, 12, 2147483647, -2147483648, -100, 100]

L = [f"// AUTO-GENERATED by gen_cmpsweep.py -- {w}-bit operand forced directly",
     "integer cs_bad, cs_i;",
     "reg signed [%d:0] cs_x;" % (w - 1),
     "task cmpsweep; begin",
     "  cs_bad = 0;",
     '  $display("CMPSWEEP forcing %s and reading %s");' % (A, Z)]
for v in TESTS:
    L.append(f"  cs_x = {v};")
    for k in range(w):
        L.append(f"  force dut.n{idx[k]} = cs_x[{k}];")
    L.append("  #20000;")          # 20 ns: the cone is ~2 ns deep
    L.append(f'  if (dut.n{zb} !== (cs_x > -1)) begin cs_bad = cs_bad + 1;')
    L.append('    $display("CMPSWEEP x=%0d sgt(x,-1) should be %0b, cone says %0b",'
             f' cs_x, (cs_x > -1), dut.n{zb}); end')
    L.append('  else $display("CMPSWEEP x=%%0d -> %%0b ok", cs_x, dut.n%d);' % zb)
for k in range(w):
    L.append(f"  release dut.n{idx[k]};")
L += ['  $display("CMPSWEEP %%0d of %d forced operands wrong", cs_bad);' % len(TESTS),
      "end endtask"]
open(os.path.join(HERE, "cmpsweep.vh"), "w").write("\n".join(L) + "\n")
print(f"cmpsweep.vh: {w}-bit operand, {len(TESTS)} forced values")
