#!/usr/bin/env python3
"""Emit cmpguard.vh: does ucmpi11 compute sgt(x,-1) correctly, on its own edge?

This is the narrowest possible question about the abs, and getting it narrow
took three wrong instruments -- all three failed the same way, by comparing two
wires that are not carrying the same transaction:

  * the board detector compared the comparator's operand against its result
    through a BUFG, and fired on seven vectors that were delivering correct
    answers;
  * a first sim guard compared the select's output read at the FAR side of a
    bd_link against its input read at the near side, and reported the mux as
    one transaction behind on every single sample;
  * a second compared the comparator's post-link output against its pre-link
    operand, which are also a link apart.

The rule that survives: BOTH WIRES PRE-LINK, SAMPLED ON THE CELL'S OWN REQUEST.
`rig_cmp_in` and `rig_cmp_z` are exactly that pair -- bdc/emit.py's probe ports
on %135__2 and %136_u, the comparator's own operand and its own result, neither
of them across a latch from the other.  The edge is the output of ucmpi11's own
matched delay chain, which is where the cell asserts its result is ready.

If this reports zero faults, the comparator is sound and the abs failure is
somewhere else.  If it reports faults, the comparator is genuinely producing a
wrong answer for an operand that was sitting right there on its input pins, and
no amount of downstream padding will fix that.
"""
import json, os, re, sys

HERE = os.environ.get("GLS_WORK") or os.path.dirname(os.path.abspath(__file__))
top = json.load(open(os.path.join(HERE, "routed.json")))["modules"]["top"]
nets = top["netnames"]

IN, OUT, CHAIN = "rig_cmp_in", "rig_cmp_z", "urig.udut.ucmpi11.udly.chain.s"


def bits(base):
    if base in nets and all(isinstance(b, int) for b in nets[base]["bits"]):
        bl = nets[base]["bits"]
        if len(bl) == 1:
            return "dut.n%d" % bl[0], 1
        return "{" + ", ".join("dut.n%d" % b for b in reversed(bl)) + "}", len(bl)
    idx = {}
    for n, nn in nets.items():
        m = re.fullmatch(re.escape(base) + r"\[(\d+)\]", n)
        if m and len(nn["bits"]) == 1 and isinstance(nn["bits"][0], int):
            idx[int(m.group(1))] = nn["bits"][0]
    if not idx:
        sys.exit(f"gen_cmpguard: no net named {base}")
    w = max(idx) + 1
    if any(k not in idx for k in range(w)):
        sys.exit(f"gen_cmpguard: {base} is missing bits")
    return "{" + ", ".join("dut.n%d" % idx[k] for k in range(w - 1, -1, -1)) + "}", w


ins, iw = bits(IN)
outs, _ = bits(OUT)
ix = sorted(int(m.group(1)) for m in
            (re.fullmatch(re.escape(CHAIN) + r"\[(\d+)\]", n) for n in nets) if m)
if not ix:
    sys.exit(f"gen_cmpguard: no delay chain at {CHAIN}")
qs, _ = bits(f"{CHAIN}[{ix[-1]}]")

L = [f"// AUTO-GENERATED by gen_cmpguard.py -- operand {iw}b, {len(ix)} delay links",
     f"wire signed [{iw-1}:0] cg_x = {ins};",
     f"wire                   cg_z = {outs};",
     f"wire                   cg_q = {qs};",
     "integer cg_n, cg_bad, cg_neg;",
     "initial begin cg_n=0; cg_bad=0; cg_neg=0; end",
     "always @(posedge cg_q) begin",
     "    cg_n = cg_n + 1;",
     "    if (cg_x < 0) cg_neg = cg_neg + 1;",
     "    if (cg_z !== (cg_x > -1)) begin",
     "        cg_bad = cg_bad + 1;",
     '        if (cg_bad <= 8) $display("CMP #%0d t=%0t x=%0d sgt(x,-1) should '
     'be %0b, cell says %0b", cg_n, $time, cg_x, (cg_x > -1), cg_z);',
     "    end",
     "end",
     "task cmpguard_report; begin",
     '    $display("CMPGUARD %0d samples (%0d with a negative operand), %0d wrong",'
     " cg_n, cg_neg, cg_bad);",
     "end endtask"]
open(os.path.join(HERE, "cmpguard.vh"), "w").write("\n".join(L) + "\n")
print(f"cmpguard.vh: operand {iw}b, sampled on ucmpi11's own delay-chain output")
