#!/usr/bin/env python3
"""Emit chan.vh: a per-channel activity probe over the compiled kernel.

nextpnr keeps the compiler's own net names, so every dataflow edge bdc/emit.py
produced is still identifiable in the routed netlist as <chan>_req / <chan>_ack
(and <chan>_data[..] for the ones that carry a payload).  This probes them all:
one transition counter per handshake wire, and the live value of every data bus,
so a run can be asked two different questions --

  "which channels stopped" (a deadlock: counter frozen), and
  "which channels are still going round with the same operands" (a livelock:
   counter climbing, data bus constant).

Both matter here, because a four-phase kernel that is not delivering results
looks identical from the outside either way.
"""
import json, os, re, sys, collections

# Where the routed inputs live and the generated files go.  Defaults to
# this directory so the scripts still work standing alone, but build.sh
# sets GLS_WORK to a per-design build dir: the sources stay in git and
# the ~900 MB of generated netlist, maps and vvp images stay out of it.
HERE = os.environ.get("GLS_WORK") or os.path.dirname(os.path.abspath(__file__))
top = json.load(open(os.path.join(HERE, "routed.json")))["modules"]["top"]
nets = top["netnames"]

PREF = "urig."
hs, data = [], collections.defaultdict(dict)
for name, nn in sorted(nets.items()):
    if not name.startswith(PREF):
        continue
    bits = nn["bits"]
    m = re.match(r"(.*)_data\[(\d+)\]$", name)
    if m and len(bits) == 1 and isinstance(bits[0], int):
        data[m.group(1)][int(m.group(2))] = bits[0]
        continue
    # A ONE-BIT channel is named `<chan>_data`, with no [0] -- and every
    # select, every branch condition and every loop index in the design is
    # one bit wide.  Matching only the subscripted form silently dropped all
    # of them, which is how a livelock traced to "the abs is wrong" could not
    # then be traced to the comparator feeding it: the deciding wire was the
    # one wire not being recorded.
    if name.endswith("_data") and len(bits) == 1 and isinstance(bits[0], int):
        data[name[:-len("_data")]][0] = bits[0]
        continue
    if (name.endswith("_req") or name.endswith("_ack")) and len(bits) == 1 \
            and isinstance(bits[0], int):
        hs.append((name, bits[0]))

# one net can carry several names; probe each net once
seen, uh = set(), []
for n, b in hs:
    if b in seen:
        continue
    seen.add(b)
    uh.append((n, b))

L = ["// AUTO-GENERATED by gen_chan.py -- %d handshake wires, %d data buses"
     % (len(uh), len(data)),
     "integer cf; integer ci;",
     "reg [31:0] ntog [0:%d];" % (len(uh) - 1),
     "reg [31:0] nprev [0:%d];" % (len(uh) - 1),
     "initial for (ci = 0; ci <= %d; ci = ci + 1) begin ntog[ci]=0; nprev[ci]=0; end"
     % (len(uh) - 1)]
for i, (_n, b) in enumerate(uh):
    L.append("always @(dut.n%d) ntog[%d] = ntog[%d] + 1;" % (b, i, i))

L.append('task dump_chan(input integer tag);')
L.append('  begin cf = $fopen($sformatf("chan_%0d.txt", tag), "w");')
for i, (n, b) in enumerate(uh):
    L.append('  $fdisplay(cf, "H %%0d %%0d %%b %%s", ntog[%d], ntog[%d]-nprev[%d], dut.n%d, "%s");'
             % (i, i, i, b, n))
for ch in sorted(data):
    bl = data[ch]
    w = max(bl) + 1
    if any(k not in bl for k in range(w)):
        continue
    cat = "{" + ", ".join("dut.n%d" % bl[k] for k in range(w - 1, -1, -1)) + "}"
    L.append('  $fdisplay(cf, "D %%0d %%b %%s", %d, %s, "%s");' % (w, cat, ch))
L.append("  $fclose(cf);")
L.append("  for (ci = 0; ci <= %d; ci = ci + 1) nprev[ci] = ntog[ci];" % (len(uh) - 1))
L.append("  end")
L.append("endtask")

open(os.path.join(HERE, "chan.vh"), "w").write("\n".join(L) + "\n")
print("handshake wires:", len(uh), " data buses:", len(data))
