#!/usr/bin/env python3
"""Emit probe.vh: a last-transition timestamp on every cell output in the rig.

When a four-phase design wedges it does not crash -- it simply stops producing
events, and the simulator runs on to the end of time reporting nothing.  The
question "where did it wedge" is therefore "which node transitioned last, and
what is every other node's last transition time relative to that".  This
records exactly that, one entry per driven cell output inside urig (the kernel
and its environment), and dumps name/value/last-transition on demand for
sorting outside.

Only outputs are probed, and only inside urig: the housekeeping ring, the
window sequencer and the JTAG shifter keep running after the rig wedges and
would otherwise bury the frontier.
"""
import json, os, sys

# Where the routed inputs live and the generated files go.  Defaults to
# this directory so the scripts still work standing alone, but build.sh
# sets GLS_WORK to a per-design build dir: the sources stay in git and
# the ~900 MB of generated netlist, maps and vvp images stay out of it.
HERE = os.environ.get("GLS_WORK") or os.path.dirname(os.path.abspath(__file__))
top = json.load(open(os.path.join(HERE, "routed.json")))["modules"]["top"]
cells = top["cells"]

OUT = {"SLICE_LUTX": ["O6", "O5"], "SELMUX2_1": ["OUT"], "SLICE_FFX": ["Q"],
       "CARRY4": ["O0", "O1", "O2", "O3", "CO0", "CO1", "CO2", "CO3"],
       "BUFGCTRL": ["O"]}

pref = sys.argv[1] if len(sys.argv) > 1 else "urig."
rows = []
for cn in sorted(cells):
    if not cn.startswith(pref):
        continue
    c = cells[cn]
    for p in OUT.get(c["type"], []):
        b = c["connections"].get(p)
        if b:
            rows.append(("n%d" % b[0], "%s/%s" % (cn, p)))

seen, uniq = set(), []
for w, n in rows:
    if w in seen:
        continue
    seen.add(w)
    uniq.append((w, n))

L = ["// AUTO-GENERATED by gen_probe.py -- %d probed nodes" % len(uniq),
     "integer pf; integer pi;",
     "reg [63:0] tlast [0:%d];" % (len(uniq) - 1),
     "initial for (pi = 0; pi <= %d; pi = pi + 1) tlast[pi] = 0;" % (len(uniq) - 1)]
for i, (w, _n) in enumerate(uniq):
    L.append("always @(dut.%s) tlast[%d] = $time;" % (w, i))
L.append("task dump_probe(input integer unused);")
L.append('  begin pf = $fopen("probe_last.txt", "w");')
for i, (w, n) in enumerate(uniq):
    L.append('  $fdisplay(pf, "%%0d %%b %%s", tlast[%d], dut.%s, "%s");' % (i, w, n))
L.append("  $fclose(pf); end")
L.append("endtask")

open(os.path.join(HERE, "probe.vh"), "w").write("\n".join(L) + "\n")
print("probed nodes:", len(uniq))
