#!/usr/bin/env python3
"""Resolve the handful of signals the testbenches watch, for THIS route.

gen.py renames every net to nNNNNN, and those numbers are a property of one
place-and-route -- they move when anything moves.  The testbenches used to
hardcode them, which meant a testbench silently belonged to one build and failed
to elaborate against the next (`Unable to bind wire/reg/memory dut.n129483`).
Failing to elaborate is the good case; a number that still resolves and now
names a different wire is the bad one.

So the testbenches name signals the way the RTL does, and this resolves them
through nets.map.  A name that has vanished is an ERROR here rather than a
missing `define discovered halfway through a run.
"""
import os, sys

HERE = os.environ.get("GLS_WORK") or os.path.dirname(os.path.abspath(__file__))

# semantic name -> the net as the RTL calls it (cells/hw/gcd_rig.v, gcd_hw.v)
WANT = {
    "HK_FB":    "hk_fb",              # housekeeping ring feedback node
    "HK_CK":    "hk_ck",              # ...and the buffered ring clock
    "POR_DONE": "por_done",
    "RIG_RST":  "rig_rst",
    "RIG_LAP":  "rig_lap",            # one pulse per completed gcd
    "RIG_ERR":  "rig_err",
    "RIG_OK":   "rig_ok",
    "MISM":     "urig.mism",          # result != expected, combinational
    "ENV_C":    "urig.p_end_req",     # the env token: kernel says it is done
    "ENV_C0":   "urig.udut.n_index_97_ack",
    "IDX0":     "idx[0]",             # vector select, forced by the testbench
    "IDX1":     "idx[1]",
    "IDX2":     "idx[2]",
    "IDX3":     "idx[3]",
}

by_name = {}
path = os.path.join(HERE, "nets.map")
for line in open(path):
    if line.startswith("#"):
        continue
    wire, _, net = line.strip().partition(" ")
    by_name.setdefault(net, wire)

out, missing = [], []
out.append("// GENERATED by gen_signals.py -- one route only, do not check in.")
out.append(f"// source: {path}")
out.append("")
for k in WANT:
    w = by_name.get(WANT[k])
    if w is None:
        missing.append((k, WANT[k]))
        continue
    out.append(f"`define {k:9} dut.{w}    // {WANT[k]}")

if missing:
    print("gen_signals.py: these nets are not in this route:", file=sys.stderr)
    for k, n in missing:
        print(f"  {k:9} expected net {n!r}", file=sys.stderr)
    print("The RTL was renamed, or the design was flattened differently.\n"
          "Fix WANT above -- do not paste a wire number in, that is what this\n"
          "script exists to stop.", file=sys.stderr)
    sys.exit(1)

open(os.path.join(HERE, "signals.vh"), "w").write("\n".join(out) + "\n")
print(f"resolved {len(WANT)} signals -> signals.vh")
