/* knapsack_drive.c -- bare-metal Cortex-A9 exhaustive-input validation
 * of the knapsack AXI harness (build/knapsack_ps/knapsack_ps_top.bit)
 * at BUS SPEED, loaded over JTAG into OCM by zynq/xsdb_arm.tcl.
 *
 * WHY: the proven xsdb route pokes the register map at ~1 ms per
 * mrd/mwr, so a full 4-phase call costs ~10 ms of JTAG overhead around
 * a ~24 us core computation, and an exhaustive 8-bit input sweep is
 * impractical. This program runs the same documented protocol from the
 * CPU itself: every poll is a single AXI round trip (~a hundred ns),
 * so the whole 256-cap sweep x REPEATS loops (~10k transactions)
 * finishes in well under a second and validates the exact shipped
 * knapsack_ps_top.bit across the FULL input space, not just the 11
 * golden caps.
 *
 * Register map (zynq/knapsack_ps_top.v, base 0x40000000):
 *   0x00 CTRL   [0]=i_req [1]=o_ack [2]=rst   (rst POWERS UP 1)
 *   0x04 STATUS [0]=i_ack (STICKY: ctrl_i_req & ~req_core -- it stays 1
 *               until the host clears CTRL.i_req; never wait for it to
 *               fall on its own)  [1]=o_req
 *   0x08 I_DATA cap[7:0]
 *   0x0C O_DATA result[15:0]
 * Protocol per call (strict RTZ; the wrapper's pulse adapter makes any
 * pacing safe -- at bus speed we are ~ns-scale anyway):
 *   I_DATA=cap; CTRL=1; poll STATUS.0==1; CTRL=0; poll STATUS.0==0;
 *   poll STATUS.1==1; read O_DATA; CTRL=2; poll STATUS.1==0; CTRL=0.
 *
 * Expected results are COMPILED IN from the golden interpreter
 * (knapsack_golden.h, generated by gen_golden.py).
 *
 * TIMING CROSS-CHECK: the A9 global timer (0xF8F00200) counts at
 * CPU_3x2x = CPU_6x4x / 2 (both 6:2:1 and 4:2:2 modes halve it; UG585
 * ch.25). After rst -system the ARM PLL is locked at its reset FDIV
 * (bench fact: PLL_STATUS=0x3f) and BootROM has not reprogrammed the
 * dividers at our catch point, so CPU_6x4x = PS_CLK(33.33 MHz) x
 * ARM_PLL FDIV / ARM_CLK_CTRL.DIVISOR. Rather than hardcode that
 * story, we RECORD the raw SLCR words (ARM_PLL_CTRL / ARM_CLK_CTRL /
 * CLK_621_TRUE) in the mailbox and let the host tcl do the arithmetic
 * and cross-check against wall time -- the same derive-from-readback
 * policy xsdb_bench.tcl uses for FCLK0.
 *
 * MAILBOX (fixed, read by zynq/xsdb_arm.tcl; last 4 KB of low OCM --
 * keep in sync with ocm.ld and the tcl):
 *   0x2F000 MAGIC     0x4B505331 "KPS1", written at start of main
 *   0x2F004 DONE      0 -> 1 when the sweep is complete (written last)
 *   0x2F008 PASS      passing transactions
 *   0x2F00C FAIL      failing transactions (incl. poll timeouts)
 *   0x2F010 TOTAL     transactions attempted
 *   0x2F014 TICKS_LO  global-timer delta around the sweep (64-bit)
 *   0x2F018 TICKS_HI
 *   0x2F01C ARM_PLL_CTRL   raw SLCR readback (clock math, host side)
 *   0x2F020 ARM_CLK_CTRL
 *   0x2F024 CLK_621_TRUE
 *   0x2F028 PROGRESS  live transaction counter (wedge diagnosis)
 *   0x2F02C ERR       first poll-timeout marker: (cap<<8)|step, 0=none
 *   0x2F030 FAILS     first 8 failures x {cap, got, want} (3 words ea)
 *
 * Caches/MMU are OFF (startup.S): every access below is strongly
 * ordered, so the volatile pointers alone give program order on the
 * AXI/OCM/timer traffic; the dmb()s are cheap insurance at the
 * boundaries that matter (data-before-req, result-after-req, mailbox
 * publish before DONE).
 */

#include "knapsack_golden.h"

#ifndef REPEATS
#define REPEATS 40              /* 40 x 256 = 10240 transactions */
#endif

#define REG(a)   (*(volatile unsigned int *)(a))

#define K_CTRL   REG(0x40000000u)
#define K_STATUS REG(0x40000004u)
#define K_IDATA  REG(0x40000008u)
#define K_ODATA  REG(0x4000000Cu)

#define GT_LO    REG(0xF8F00200u)   /* A9 global timer, PERIPHBASE+0x200 */
#define GT_HI    REG(0xF8F00204u)
#define GT_CTRL  REG(0xF8F00208u)

#define SLCR_ARM_PLL_CTRL REG(0xF8000100u)
#define SLCR_ARM_CLK_CTRL REG(0xF8000120u)
#define SLCR_CLK_621_TRUE REG(0xF80001C4u)

#define MB ((volatile unsigned int *)0x0002F000u)
enum {
    MB_MAGIC, MB_DONE, MB_PASS, MB_FAIL, MB_TOTAL,
    MB_TICKS_LO, MB_TICKS_HI,
    MB_ARM_PLL, MB_ARM_CLK, MB_CLK621,
    MB_PROGRESS, MB_ERR,
    MB_FAILS                    /* 8 x {cap, got, want} from here */
};
#define MB_MAGIC_VAL 0x4B505331u    /* "KPS1" */
#define MAX_FAIL_REC 8

/* Poll budget: one iteration is an uncached AXI read + a few uncached
 * OCM fetches (order 1 us); the core call is ~24 us, so 2M iterations
 * (~seconds) only trips if the core is genuinely wedged. */
#define POLL_LIMIT 2000000u

static inline void dmb(void) { __asm__ volatile("dmb" ::: "memory"); }

static unsigned long long gt_read(void)
{
    unsigned int hi, lo, hi2;
    do {
        hi  = GT_HI;
        lo  = GT_LO;
        hi2 = GT_HI;
    } while (hi != hi2);
    return ((unsigned long long)hi << 32) | lo;
}

static void delay_ticks(unsigned int t)
{
    unsigned long long t0 = gt_read();
    while (gt_read() - t0 < t) { }
}

/* Poll STATUS until (STATUS & mask) == want; 1 on success. */
static int poll_status(unsigned int mask, unsigned int want)
{
    unsigned int i;
    for (i = 0; i < POLL_LIMIT; i++) {
        if ((K_STATUS & mask) == want)
            return 1;
    }
    return 0;
}

/* One full 4-phase call. Returns the step number that timed out
 * (1..4), or 0 on success with *got filled in. */
static int knapsack_call(unsigned int cap, unsigned int *got)
{
    K_IDATA = cap;              /* data valid before req rise */
    dmb();
    K_CTRL = 0x1;               /* i_req = 1 */
    if (!poll_status(0x1, 0x1)) return 1;   /* sticky i_ack rise */
    K_CTRL = 0x0;               /* drop i_req (input RTZ) */
    if (!poll_status(0x1, 0x0)) return 2;   /* sticky i_ack clears */
    if (!poll_status(0x2, 0x2)) return 3;   /* o_req rise */
    dmb();
    *got = K_ODATA & 0xFFFFu;
    dmb();
    K_CTRL = 0x2;               /* o_ack = 1 (mirrors o_req in the PL) */
    if (!poll_status(0x2, 0x0)) return 4;   /* o_req fall = RTZ done */
    K_CTRL = 0x0;               /* drop o_ack: 4-phase complete */
    return 0;
}

/* Recovery after a timeout: pulse the core reset and settle. Re-zeroes
 * the core (knapsack holds no state across calls), so the sweep can
 * continue; the failure itself has already been recorded. */
static void core_reset_pulse(void)
{
    K_CTRL = 0x4;               /* rst = 1, req/ack low */
    delay_ticks(20000);         /* ~100 us at any plausible GT rate */
    K_CTRL = 0x0;
    delay_ticks(20000);
}

void main(void)
{
    unsigned int i;
    for (i = 0; i < MB_FAILS + 3u * MAX_FAIL_REC; i++)
        MB[i] = 0;
    MB[MB_MAGIC] = MB_MAGIC_VAL;
    dmb();

    MB[MB_ARM_PLL] = SLCR_ARM_PLL_CTRL;
    MB[MB_ARM_CLK] = SLCR_ARM_CLK_CTRL;
    MB[MB_CLK621]  = SLCR_CLK_621_TRUE;

    GT_CTRL = 0x1;              /* enable, no prescale, no comparator */
    dmb();

    /* CTRL powers up 0x4 (rst=1): release the core and let it settle
     * (invariant: reset hold/settle >= 50 ns; this is ~100 us). */
    K_CTRL = 0x0;
    delay_ticks(20000);

    unsigned int pass = 0, fail = 0, total = 0, nrec = 0;

    unsigned long long t0 = gt_read();

    unsigned int rep, cap;
    for (rep = 0; rep < REPEATS; rep++) {
        for (cap = 0; cap < 256; cap++) {
            unsigned int got = 0xFFFFFFFFu;
            int step = knapsack_call(cap, &got);
            unsigned int want = knapsack_golden[cap];
            if (step == 0 && got == want) {
                pass++;
            } else {
                fail++;
                if (step != 0 && MB[MB_ERR] == 0)
                    MB[MB_ERR] = (cap << 8) | (unsigned int)step;
                if (nrec < MAX_FAIL_REC) {
                    MB[MB_FAILS + 3u * nrec + 0] = cap;
                    MB[MB_FAILS + 3u * nrec + 1] = got;
                    MB[MB_FAILS + 3u * nrec + 2] = want;
                    nrec++;
                }
                if (step != 0)
                    core_reset_pulse();
            }
            total++;
            MB[MB_PROGRESS] = total;
        }
    }

    unsigned long long ticks = gt_read() - t0;

    MB[MB_PASS]     = pass;
    MB[MB_FAIL]     = fail;
    MB[MB_TOTAL]    = total;
    MB[MB_TICKS_LO] = (unsigned int)ticks;
    MB[MB_TICKS_HI] = (unsigned int)(ticks >> 32);
    dmb();
    MB[MB_DONE] = 1;            /* publish: everything above is visible */
    dmb();
    /* startup.S parks the CPU in wfe after return */
}
