#!/usr/bin/env bash
# Close the loop: route, measure, apply, RE-ROUTE, keep only what survived.
#
#   ./verify/resize.sh
#
# -- why this is a search and not a calculation -------------------------------
#
# verify/tighten.py says what each matched delay should be for the route that
# was actually produced.  The obvious thing is to apply that answer and stop.
# The obvious thing does not work, and it is worth being precise about why.
#
# The recommendation is the SMALLEST length meeting the guardband, so applying
# it leaves essentially zero margin by construction.  Applying it also changes
# the netlist, which moves the placement, which changes the routing that the
# recommendation was measured against.  Run naively on this design, round 1
# proposes UMUX 4 -> 0 and UMEM_UCO 12 -> 8; round 2 then reports umux at
# -485 ps and the memory's clock-to-out at -59 ps.  The proposal was correct
# about the route it saw and wrong about the route it caused.
#
# So: propose one change, re-route, and keep it only if the design still meets
# every constraint.  Coordinate descent with verification, which terminates
# because lengths only ever decrease and are bounded below by zero, and which
# ends holding an assignment that has actually been routed and checked rather
# than one that was extrapolated.
#
# What it produces is valid for THIS design on THIS toolchain and expires the
# moment anything upstream of place-and-route changes.  That is not a caveat
# on the method, it is the method: matched delays are a property of a build.
set -u
cd "$(dirname "$0")/.."

# Same redirect flow.sh takes, and for the same reason: every artifact here is
# named soak.*, so a generated top must not read the hand-written soak design's
# SDF.  Left hardcoded, this read a STALE build/pnr/soak.sdf while flow.sh was
# routing into build/pnr/<name>/, and proposed BD_SZ_UMEM_UCO -- soak_top's
# bd_mem instance -- for a design whose port is uport.umem0.  resize.sh's own
# "that delay cannot be driven" check caught it, which is the only reason this
# is a note and not a wrong bitstream.
OUT=${BD_OUT:-build/pnr}
# Per-design too: two designs sharing one resize history would ratchet each
# other's proposals.  Follows BD_OUT for the same reason $OUT does.
HIST=${BD_OUT:-build}/resize
mkdir -p $HIST
rm -f $OUT/sizes.vh $HIST/*.log $HIST/*.vh

# The design under test, same opt-in spelling flow.sh uses.  Exported, because
# flow.sh is what reads it.
TOP_V="${BD_TOP_V:-verify/soak_top.v}"
export BD_TOP_V="$TOP_V"
[ -f "$TOP_V" ] || { echo "BD_TOP_V=$TOP_V does not exist"; exit 2; }

# -- which delays exist is a property of the SOURCE ---------------------------
#
# This was a hardcoded list of the five keys soak_top.v happens to have, and a
# hardcoded copy of their placeholder values.  That is fine right up until the
# design under test is a GENERATED one, and then it is the worst kind of wrong:
# a key not in the list is never proposed, never applied and never reverted, so
# the loop settles, prints a verified assignment, and reports success having
# silently skipped a delay entirely.  The list has to come from the same place
# the defaults do -- the `ifndef / `define pair in the source -- or the two can
# disagree and nothing says so.
declare -A cur prop
KEYS=()
while read -r k v; do
    if [ -n "${cur[$k]+x}" ] && [ "${cur[$k]}" != "$v" ]; then
        echo "$k has two different placeholder values in the source " \
             "(${cur[$k]} and $v).  Which one is the baseline is not this" \
             "script's guess to make."
        exit 2
    fi
    [ -n "${cur[$k]+x}" ] || KEYS+=("$k")
    cur[$k]=$v
done < <(grep -h '^[[:space:]]*`define[[:space:]]\+BD_SZ_' rtl/*.v "$TOP_V" \
         | awk '{print $2, $3}' | sort -u)

if [ ${#KEYS[@]} -eq 0 ]; then
    echo "no \`BD_SZ_* placeholders found in rtl/*.v or $TOP_V -- either this"
    echo "design has no matched delays, or they were inlined as literals, which"
    echo "is the one thing that makes this whole mechanism a no-op."
    exit 2
fi
echo "delays found in source: ${KEYS[*]}"

SIZEFILE=$HIST/sizes.vh
export BD_SIZES=$SIZEFILE
# Exported once, here, and never unset for the rest of this script's life:
# every ./flow.sh call below -- baseline, each try, and the final re-route --
# therefore always takes flow.sh's explicit-BD_SIZES branch, never its
# default auto-tighten branch.  That is what keeps flow.sh's default path
# (which runs THIS script) from calling back into itself; flow.sh's own
# BD_TIGHTEN_RUNNING check is the belt-and-braces for the day this line
# stops being true.

write_sizes() {                       # write the current assignment
    local k                           # NOT optional: without it this clobbers
    {                                 # the caller's loop variable
        echo "// GENERATED by verify/resize.sh -- one build's answer, not a constant."
        for k in "${KEYS[@]}"; do echo "\`define $k ${cur[$k]}"; done
    } > "$SIZEFILE"
}

# route + check; 0 = the design meets every constraint
#
# "every constraint" has to mean every constraint check.sh gates on, not just
# the one that produced the proposal.  This ran flow.sh and tighten.py and
# stopped there, which means it verified RULE D only -- and check.sh's own
# comment says rule D is a one-sided screen whose numbers are not safe to act
# on.  Rule E, the one that measures from a common launch and is the only one
# that emits padding, was never consulted.  A loop that only ever SHRINKS
# delays and cannot see rule E will happily shrink a delay that exists solely
# to satisfy rule E, re-break it, and report a verified assignment: exactly
# what would have happened to BD_SZ_UDEC, which had to go 4 -> 16 to close
# umux.  Any accept test that cannot observe the constraint a length was
# chosen for will eventually undo that length.
attempt() {
    local tag=$1
    ./flow.sh > "$HIST/flow_$tag.log" 2>&1 || return 2
    # NAME THE SDF.  tighten.py defaults to build/pnr/soak.sdf, so with BD_OUT
    # set this measured a stale route from a different design.
    python3 verify/tighten.py --emit "$HIST/prop_$tag.vh" "$OUT/soak.sdf" \
        > "$HIST/tighten_$tag.log" 2>&1 || return 1
    python3 verify/skew.py "$OUT/soak.sdf" > "$HIST/skew_$tag.log" 2>&1
}

read_prop() {                         # load a proposal into prop[]
    local f=$1 k v
    for k in "${KEYS[@]}"; do prop[$k]=${cur[$k]}; done
    while read -r _ k v; do
        if [ -z "${cur[$k]+x}" ]; then
            # tighten.py names a delay after the instance path it found it at.
            # A name it proposes that no source file defines means the two
            # halves of the mechanism have drifted: the length would be written
            # to sizes.vh, read by nothing, and the loop would report success
            # having changed nothing.  Never let that be quiet.
            echo "tighten.py proposes $k = $v, but no \`define $k exists in"
            echo "rtl/*.v or $TOP_V.  That delay cannot be driven, so this"
            echo "search cannot honestly claim to have sized it."
            exit 1
        fi
        prop[$k]=$v
    done < <(grep '^`define' "$f" | sed 's/`define //' | awk '{print "d", $1, $2}')
}

show() { local k out=""; for k in "${KEYS[@]}"; do
             out="$out ${k#BD_SZ_}=${cur[$k]}"; done; echo "$out"; }

# -- baseline: the placeholders, already read out of the source above --------
write_sizes
echo "baseline (the placeholders):$(show)"
if ! attempt base; then
    echo "the placeholder build does not meet its own constraints -- nothing to"
    echo "tighten from.  See $HIST/tighten_base.log"
    grep VIOLATION "$HIST/tighten_base.log" | head
    exit 1
fi
cp "$HIST/prop_base.vh" "$HIST/prop_last.vh"
echo "baseline routes and passes."
echo

routes=1
sweep=0
while : ; do
    sweep=$((sweep + 1))
    read_prop "$HIST/prop_last.vh"

    changed=0
    for k in "${KEYS[@]}"; do
        want=${prop[$k]}
        [ "$want" -ge "${cur[$k]}" ] && continue      # only ever tighten
        was=${cur[$k]}
        cur[$k]=$want
        write_sizes
        routes=$((routes + 1))
        if attempt "try_${k}_${want}"; then
            cp "$HIST/prop_try_${k}_${want}.vh" "$HIST/prop_last.vh"
            printf "  %-20s %2d -> %-2d  kept\n" "${k#BD_SZ_}" "$was" "$want"
            changed=1
        else
            cur[$k]=$was
            write_sizes
            reason=$(grep -m1 VIOLATION "$HIST/tighten_try_${k}_${want}.log" \
                     | sed 's/^ *//;s/  */ /g')
            printf "  %-20s %2d -> %-2d  REVERTED\n" "${k#BD_SZ_}" "$was" "$want"
            printf "  %-20s          %s\n" "" "${reason:-place-and-route failed}"
        fi
    done

    [ $changed -eq 0 ] && break
    echo "  -- sweep $sweep done:$(show)"
done

write_sizes
./flow.sh > "$HIST/flow_final.log" 2>&1
python3 verify/tighten.py --emit "$HIST/final_prop.vh" "$OUT/soak.sdf" > "$HIST/tighten_final.log" 2>&1
final=$?

echo
echo "settled after $sweep sweep(s), $routes place-and-route runs"
echo "verified assignment:$(show)"
echo "written to $SIZEFILE -- pass it back with BD_SIZES=$SIZEFILE ./flow.sh"
if [ $final -ne 0 ]; then
    echo "but the final re-route does not check out -- see $HIST/tighten_final.log"
    exit 1
fi
echo
echo "Every length above was applied, re-routed and re-checked, not "
echo "extrapolated.  It is one build's answer and expires with the build."
