#!/usr/bin/env bash
# Close the loop: route, measure, apply, RE-ROUTE, keep only what survived.
#
#   ./verify/resize.sh
#
# -- why this is a search and not a calculation -------------------------------
#
# verify/tighten.py says what each matched delay should be for the route that
# was actually produced.  The obvious thing is to apply that answer and stop.
# The obvious thing does not work, and it is worth being precise about why.
#
# The recommendation is the SMALLEST length meeting the guardband, so applying
# it leaves essentially zero margin by construction.  Applying it also changes
# the netlist, which moves the placement, which changes the routing that the
# recommendation was measured against.  Run naively on this design, round 1
# proposes UMUX 4 -> 0 and UMEM_UCO 12 -> 8; round 2 then reports umux at
# -485 ps and the memory's clock-to-out at -59 ps.  The proposal was correct
# about the route it saw and wrong about the route it caused.
#
# So: propose one change, re-route, and keep it only if the design still meets
# every constraint.  Coordinate descent with verification, which terminates
# because lengths only ever decrease and are bounded below by zero, and which
# ends holding an assignment that has actually been routed and checked rather
# than one that was extrapolated.
#
# What it produces is valid for THIS design on THIS toolchain and expires the
# moment anything upstream of place-and-route changes.  That is not a caveat
# on the method, it is the method: matched delays are a property of a build.
set -u
cd "$(dirname "$0")/.."

# Same redirect flow.sh takes, and for the same reason: every artifact here is
# named soak.*, so a generated top must not read the hand-written soak design's
# SDF.  Left hardcoded, this read a STALE build/pnr/soak.sdf while flow.sh was
# routing into build/pnr/<name>/, and proposed BD_SZ_UMEM_UCO -- soak_top's
# bd_mem instance -- for a design whose port is uport.umem0.  resize.sh's own
# "that delay cannot be driven" check caught it, which is the only reason this
# is a note and not a wrong bitstream.
OUT=${BD_OUT:-build/pnr}
# Per-design too: two designs sharing one resize history would ratchet each
# other's proposals.  Follows BD_OUT for the same reason $OUT does.
HIST=${BD_OUT:-build}/resize
mkdir -p $HIST
rm -f $OUT/sizes.vh $HIST/*.log $HIST/*.vh

# The design under test, same opt-in spelling flow.sh uses.  Exported, because
# flow.sh is what reads it.
TOP_V="${BD_TOP_V:-verify/soak_top.v}"
export BD_TOP_V="$TOP_V"
[ -f "$TOP_V" ] || { echo "BD_TOP_V=$TOP_V does not exist"; exit 2; }

# -- which delays exist is a property of the SOURCE ---------------------------
#
# This was a hardcoded list of the five keys soak_top.v happens to have, and a
# hardcoded copy of their placeholder values.  That is fine right up until the
# design under test is a GENERATED one, and then it is the worst kind of wrong:
# a key not in the list is never proposed, never applied and never reverted, so
# the loop settles, prints a verified assignment, and reports success having
# silently skipped a delay entirely.  The list has to come from the same place
# the defaults do -- the `ifndef / `define pair in the source -- or the two can
# disagree and nothing says so.
declare -A cur prop
KEYS=()
while read -r k v; do
    if [ -n "${cur[$k]+x}" ] && [ "${cur[$k]}" != "$v" ]; then
        echo "$k has two different placeholder values in the source " \
             "(${cur[$k]} and $v).  Which one is the baseline is not this" \
             "script's guess to make."
        exit 2
    fi
    [ -n "${cur[$k]+x}" ] || KEYS+=("$k")
    cur[$k]=$v
done < <(grep -h '^[[:space:]]*`define[[:space:]]\+BD_SZ_' rtl/*.v "$TOP_V" \
         | awk '{print $2, $3}' | sort -u)

if [ ${#KEYS[@]} -eq 0 ]; then
    echo "no \`BD_SZ_* placeholders found in rtl/*.v or $TOP_V -- either this"
    echo "design has no matched delays, or they were inlined as literals, which"
    echo "is the one thing that makes this whole mechanism a no-op."
    exit 2
fi
echo "delays found in source: ${KEYS[*]}"

SIZEFILE=$HIST/sizes.vh
export BD_SIZES=$SIZEFILE
# Exported once, here, and never unset for the rest of this script's life:
# every ./flow.sh call below -- baseline, each try, and the final re-route --
# therefore always takes flow.sh's explicit-BD_SIZES branch, never its
# default auto-tighten branch.  That is what keeps flow.sh's default path
# (which runs THIS script) from calling back into itself; flow.sh's own
# BD_TIGHTEN_RUNNING check is the belt-and-braces for the day this line
# stops being true.

write_sizes() {                       # write the current assignment
    local k                           # NOT optional: without it this clobbers
    {                                 # the caller's loop variable
        echo "// GENERATED by verify/resize.sh -- one build's answer, not a constant."
        for k in "${KEYS[@]}"; do echo "\`define $k ${cur[$k]}"; done
    } > "$SIZEFILE"
}

# route + check; 0 = the design meets every constraint
#
# "every constraint" has to mean every constraint check.sh gates on, not just
# the one that produced the proposal.  This ran flow.sh and tighten.py and
# stopped there, which means it verified RULE D only -- and check.sh's own
# comment says rule D is a one-sided screen whose numbers are not safe to act
# on.  Rule E, the one that measures from a common launch and is the only one
# that emits padding, was never consulted.  A loop that only ever SHRINKS
# delays and cannot see rule E will happily shrink a delay that exists solely
# to satisfy rule E, re-break it, and report a verified assignment: exactly
# what would have happened to BD_SZ_UDEC, which had to go 4 -> 16 to close
# umux.  Any accept test that cannot observe the constraint a length was
# chosen for will eventually undo that length.
#
# THE SAME SENTENCE IS TRUE ABOUT ROUTES, and that half was missing.  flow.sh
# is deterministic, so "it passed" here has always meant "it passed on the one
# route nextpnr produces for this netlist" -- and a margin is not a property of
# a netlist, it is a property of a route.  Measured on the arbitrated memory
# port: this loop settled UPORT_UMEM0_USETUP at 5 links, on a route where rule
# B had 10 ps of margin.  Re-routed under four other seeds, that same size gave
# -108, -615, -719 ps and one pass.  At the untightened 8 links, twelve
# measurements over six seeds were all ok with 660-2405 ps.  So the size was
# not merely lucky, it was wrong, and nothing in the loop could have said so.
#
# BD_RESIZE_SEEDS=N asks for N routes per candidate and keeps a size only if
# ALL of them meet every constraint.  Default 1, which is exactly the old
# behaviour: N routes cost N times the place-and-route, and that is a real
# price to pay on every candidate in every sweep, so it is the caller's call.
# Pay it for anything whose numbers are going to be quoted or built.
#
# BE HONEST ABOUT WHAT N=3 BUYS.  On the same design it vetoed one shrink that
# N=1 had accepted -- and the assignment it settled on instead still violated
# rule B on three of eight fresh routes.  Three samples are weak evidence
# against a defect that appears on about two routes in five; they miss it
# roughly a fifth of the time, and they did.  This knob raises the bar.  It
# does not clear it, and a length it keeps is still not a length to trust
# without a guardband.  See bdc/AUDIT.md section 7.
SEEDS=${BD_RESIZE_SEEDS:-1}
# BD_RESIZE_SLACK=P (ps) is the other half of the same bargain.  N routes say
# whether a length holds on N routes; they say nothing about how far from the
# edge it sits on each, and a length kept with 20 ps to spare on all three is
# short on a fourth as soon as the router moves one wire.  Measured on
# xorshift_round under v8 placement, N=3: one DACK kept at 1 link with +171 ps
# on the search's route came back at -23 and -19 ps on two of three fresh
# seeds.  With P, tighten.py widens every guardband by P during the search
# only, so what is kept passed with at least P ps of physical margin on every
# route it was checked on.  The audits that gate a build run with P=0.  Costs
# up to one link (~274 ps) on a delay in P/274 of cases; buys the fresh-seed
# pass rate.
#
# Default 300, from the spread itself.  Over 15 xorshift_round rows (v8/v9
# placement, 9- and 25-row columns, fusion on and off, caps 4 and 8; four
# routes each, one of them the search's own), the margin of a rule-A or -H
# row with fewer than 1000 ps to spare moved by 100-290 ps between routes
# in all but two cases (357 and 477 ps, both on rows with 390+ ps in hand).
# The one fresh-seed FAILURE in that set was a row kept at +212 ps under the
# old default of 150 that came back at -11 ps: 150 is inside the spread, 300
# is at its edge.  A P that covered the two outliers would be 500 and cost
# another link on about half of the tight delays; not paid.
SLACK=${BD_RESIZE_SLACK:-300}
attempt() {
    local tag=$1 s=2
    ./flow.sh > "$HIST/flow_$tag.log" 2>&1 || return 2
    # NAME THE SDF.  tighten.py defaults to build/pnr/soak.sdf, so with BD_OUT
    # set this measured a stale route from a different design.
    python3 verify/tighten.py --slack "$SLACK" --emit "$HIST/prop_$tag.vh" "$OUT/soak.sdf" \
        > "$HIST/tighten_$tag.log" 2>&1 || return 1
    python3 verify/skew.py "$OUT/soak.sdf" > "$HIST/skew_$tag.log" 2>&1 || return 1
    # The PROPOSAL always comes from the unseeded route above, so the loop's
    # answer stays reproducible; the seeded routes below only ever veto.
    # A seed's proposal is never applied as a proposal (see above); it is kept
    # so that repair() can read which delay a seed found short.
    while [ "$s" -le "$SEEDS" ]; do
        NEXTPNR_SEED=$s ./flow.sh > "$HIST/flow_${tag}_s$s.log" 2>&1 || return 2
        python3 verify/tighten.py --slack "$SLACK" --emit "$HIST/prop_${tag}_s$s.vh" "$OUT/soak.sdf" \
            > "$HIST/tighten_${tag}_s$s.log" 2>&1 || return 1
        python3 verify/skew.py "$OUT/soak.sdf" \
            > "$HIST/skew_${tag}_s$s.log" 2>&1 || return 1
        s=$((s + 1))
    done
}

read_prop() {                         # load a proposal into prop[]
    local f=$1 k v
    for k in "${KEYS[@]}"; do prop[$k]=${cur[$k]}; done
    while read -r _ k v; do
        if [ -z "${cur[$k]+x}" ]; then
            # tighten.py names a delay after the instance path it found it at.
            # A name it proposes that no source file defines means the two
            # halves of the mechanism have drifted: the length would be written
            # to sizes.vh, read by nothing, and the loop would report success
            # having changed nothing.  Never let that be quiet.
            echo "tighten.py proposes $k = $v, but no \`define $k exists in"
            echo "rtl/*.v or $TOP_V.  That delay cannot be driven, so this"
            echo "search cannot honestly claim to have sized it."
            exit 1
        fi
        prop[$k]=$v
    done < <(grep '^`define' "$f" | sed 's/`define //' | awk '{print "d", $1, $2}')
}

show() { local k out=""; for k in "${KEYS[@]}"; do
             out="$out ${k#BD_SZ_}=${cur[$k]}"; done; echo "$out"; }

total() { local k t=0; for k in "${KEYS[@]}"; do t=$((t + cur[$k])); done; echo $t; }

# -- a veto that is not about the delay being tried ---------------------------
#
# Shrinking one delay changes the netlist, so it moves the placement of
# everything, and a delay that was kept at its exact measured length on the
# old route can come up short on the new one.  Reverting the TRIED delay for
# that is the wrong response, and it compounds: every later shrink moves the
# route the same way and fails the same way, so the tried delay is parked at
# whatever length it had.  Measured on bdc/fusion_bench.py's xorshift_round:
# uxori_9 settled at 5 links with 96 ps of margin, after which 34 candidate
# shrinks of uxori_4 and uxori_14 were all vetoed by uxori_9 going -17..-761
# ps on the re-route, and uxori_4 kept 37 links of a 6-link need -- ten
# nanoseconds of latency, on a kernel whose whole round is fourteen.
#
# So when the route's violators are OTHER delays, pad them to what tighten.py
# asks for on the new route and check again.  The result is kept only if the
# sum of all lengths still went down: that is what keeps this a descent (the
# total strictly decreases on every kept step, so it terminates) and what
# stops a shrink of one element from buying itself with a pad of ten.  A veto
# from skew.py, or on the tried delay itself, is a real veto and is bisected
# as before.
#
# The route that vetoed may be a confirmation seed's, and that is the same
# case, not a stronger veto: the tried delay held on every route, and some
# other delay -- already at its length in the baseline, checked there on the
# same seeds -- came up P ps short once the netlist moved under it.  Treated
# as a veto of the tried delay it parked uxori_14 at 8 links on a 5-link
# need (the harness pipe's DACK, at 0, wanted 1 on seed 2 of the 5-link
# candidate and nowhere else), and the shrink from 8 never came back: ~1.1 ns
# of interval on a 6.4 ns cycle.
#
# And the padded route is a new route, so it can come up short somewhere else
# -- or in the same place by more, since what tighten.py asked for was the
# need on the route it saw.  One round of padding parked uxori_9 at 43 links
# on a 4-link need (fusion off, v9, 25 rows): every candidate below 43 was
# vetoed by uxori_4 wanting 6, padded to 6, and vetoed again by uxori_4
# wanting 7 on the padded route.  So pad up to REPAIR_ROUNDS times, each
# round reading the latest route's asks, under the same total-decreases
# budget throughout.
REPAIR_ROUNDS=${BD_RESIZE_REPAIR_ROUNDS:-3}

veto_of() {                           # veto_of TAG -> which tighten.py log vetoed it
    local tag=$1 s=2
    [ -f "$HIST/prop_$tag.vh" ] || return 1          # the unseeded route failed
    if [ -f "$HIST/skew_$tag.log" ]; then           # tighten.py passed the unseeded route
        while [ "$s" -le "$SEEDS" ]; do
            [ -f "$HIST/prop_${tag}_s$s.vh" ] || return 1   # that seed did not route
            [ -f "$HIST/skew_${tag}_s$s.log" ] || break     # its tighten.py vetoed
            s=$((s + 1))
        done
        [ "$s" -le "$SEEDS" ] || return 1           # every tighten.py passed; the veto is skew.py's
        tag=${tag}_s$s
    fi
    grep -q VIOLATION "$HIST/tighten_$tag.log" 2>/dev/null || return 1
    echo "$tag"
}

repair() {                            # repair KEY TAG WAS WANT
    local k=$1 tag=$2 was=$3 want=$4 y v budget n veto round=0 rtag
    local -A save
    rtag=$tag
    budget=$(( $(total) + was - want ))
    while [ $round -lt "$REPAIR_ROUNDS" ]; do
        veto=$(veto_of "$rtag") || break
        n=0
        while read -r _ y v; do
            [ -n "${cur[$y]+x}" ] || continue
            [ "$v" -gt "${cur[$y]}" ] || continue
            [ "$y" = "$k" ] && break 2                # the tried delay is the one that is short
            [ -n "${save[$y]+x}" ] || save[$y]=${cur[$y]}
            cur[$y]=$v
            n=$((n + 1))
        done < <(grep '^`define' "$HIST/prop_$veto.vh" | sed 's/`define //' | awk '{print "d", $1, $2}')
        [ $n -gt 0 ] || break                        # a violation with no knob to pad
        [ "$(total)" -lt "$budget" ] || break
        round=$((round + 1))
        rtag=${tag}_r$round
        write_sizes
        routes=$((routes + 1))
        if attempt "$rtag"; then
            cp "$HIST/prop_$rtag.vh" "$HIST/prop_last.vh"
            for y in "${!save[@]}"; do
                printf "  %-20s %2d -> %-2d  padded, so that the shrink below could stand\n" \
                       "${y#BD_SZ_}" "${save[$y]}" "${cur[$y]}"
            done
            return 0
        fi
    done
    for y in "${!save[@]}"; do cur[$y]=${save[$y]}; done
    return 1
}

# -- baseline: the placeholders, already read out of the source above --------
write_sizes
echo "baseline (the placeholders):$(show)"
if ! attempt base; then
    echo "the placeholder build does not meet its own constraints -- nothing to"
    echo "tighten from.  See $HIST/tighten_base.log"
    grep VIOLATION "$HIST/tighten_base.log" | head
    exit 1
fi
cp "$HIST/prop_base.vh" "$HIST/prop_last.vh"
echo "baseline routes and passes."
echo

routes=1
sweep=0
while : ; do
    sweep=$((sweep + 1))
    read_prop "$HIST/prop_last.vh"

    changed=0
    for k in "${KEYS[@]}"; do
        want=${prop[$k]}
        [ "$want" -ge "${cur[$k]}" ] && continue      # only ever tighten
        was=${cur[$k]}
        while [ "$want" -lt "$was" ]; do
            cur[$k]=$want
            write_sizes
            routes=$((routes + 1))
            if attempt "try_${k}_${want}"; then
                cp "$HIST/prop_try_${k}_${want}.vh" "$HIST/prop_last.vh"
                printf "  %-20s %2d -> %-2d  kept\n" "${k#BD_SZ_}" "$was" "$want"
                changed=1
                break
            fi
            if repair "$k" "try_${k}_${want}" "$was" "$want"; then
                printf "  %-20s %2d -> %-2d  kept\n" "${k#BD_SZ_}" "$was" "$want"
                changed=1
                break
            fi
            cur[$k]=$was
            write_sizes
            # The veto may have come from a confirmation seed, not from the
            # unseeded route, so look in every log this candidate produced.
            reason=$(cat "$HIST"/tighten_try_"${k}"_"${want}".log \
                         "$HIST"/tighten_try_"${k}"_"${want}"_s*.log 2>/dev/null |
                     grep -v "^search slack" | grep -m1 VIOLATION | sed 's/^ *//;s/  */ /g')
            printf "  %-20s %2d -> %-2d  REVERTED\n" "${k#BD_SZ_}" "$was" "$want"
            printf "  %-20s          %s\n" "" "${reason:-place-and-route failed}"
            want=$(((want + was + 1) / 2))
        done
    done

    [ $changed -eq 0 ] && break
    echo "  -- sweep $sweep done:$(show)"
done

write_sizes
attempt final
final=$?

echo
if [ "$SEEDS" -gt 1 ]; then
    echo "settled after $sweep sweep(s), $routes candidate(s) x $SEEDS route(s) each"
else
    echo "settled after $sweep sweep(s), $routes place-and-route runs"
    echo "ONE ROUTE PER CANDIDATE -- these lengths are known to hold on the route"
    echo "flow.sh happens to produce and on no other.  BD_RESIZE_SEEDS=N to confirm."
fi
echo "verified assignment:$(show)"
echo "written to $SIZEFILE -- pass it back with BD_SIZES=$SIZEFILE ./flow.sh"
if [ $final -ne 0 ]; then
    echo "but the final re-route does not check out -- see $HIST/tighten_final.log"
    exit 1
fi
echo
echo "Every length above was applied, re-routed and re-checked, not "
echo "extrapolated.  It is one build's answer and expires with the build."
