#!/usr/bin/env bash
# Close the loop: route, measure, apply, RE-ROUTE, keep only what survived.
#
#   ./verify/resize.sh
#
# -- why this is a search and not a calculation -------------------------------
#
# verify/tighten.py says what each matched delay should be for the route that
# was actually produced.  The obvious thing is to apply that answer and stop.
# The obvious thing does not work, and it is worth being precise about why.
#
# The recommendation is the SMALLEST length meeting the guardband, so applying
# it leaves essentially zero margin by construction.  Applying it also changes
# the netlist, which moves the placement, which changes the routing that the
# recommendation was measured against.  Run naively on this design, round 1
# proposes UMUX 4 -> 0 and UMEM_UCO 12 -> 8; round 2 then reports umux at
# -485 ps and the memory's clock-to-out at -59 ps.  The proposal was correct
# about the route it saw and wrong about the route it caused.
#
# So: propose one change, re-route, and keep it only if the design still meets
# every constraint.  Coordinate descent with verification, which terminates
# because lengths only ever decrease and are bounded below by zero, and which
# ends holding an assignment that has actually been routed and checked rather
# than one that was extrapolated.
#
# What it produces is valid for THIS design on THIS toolchain and expires the
# moment anything upstream of place-and-route changes.  That is not a caveat
# on the method, it is the method: matched delays are a property of a build.
set -u
cd "$(dirname "$0")/.."

OUT=build/pnr
HIST=build/resize
mkdir -p $HIST
rm -f $OUT/sizes.vh $HIST/*.log $HIST/*.vh

KEYS=(BD_SZ_UDEC BD_SZ_UMERGE BD_SZ_UMUX BD_SZ_UMEM_USETUP BD_SZ_UMEM_UCO)
declare -A cur prop

SIZEFILE=$HIST/sizes.vh
export BD_SIZES=$SIZEFILE

write_sizes() {                       # write the current assignment
    local k                           # NOT optional: without it this clobbers
    {                                 # the caller's loop variable
        echo "// GENERATED by verify/resize.sh -- one build's answer, not a constant."
        for k in "${KEYS[@]}"; do echo "\`define $k ${cur[$k]}"; done
    } > "$SIZEFILE"
}

# route + check; 0 = the design meets every constraint
attempt() {
    local tag=$1
    ./flow.sh > "$HIST/flow_$tag.log" 2>&1 || return 2
    python3 verify/tighten.py --emit "$HIST/prop_$tag.vh" \
        > "$HIST/tighten_$tag.log" 2>&1
}

read_prop() {                         # load a proposal into prop[]
    local f=$1 k v
    for k in "${KEYS[@]}"; do prop[$k]=${cur[$k]}; done
    while read -r _ k v; do
        [ -n "${cur[$k]+x}" ] && prop[$k]=$v
    done < <(grep '^`define' "$f" | sed 's/`define //' | awk '{print "d", $1, $2}')
}

show() { local k out=""; for k in "${KEYS[@]}"; do
             out="$out ${k#BD_SZ_}=${cur[$k]}"; done; echo "$out"; }

# -- baseline: the placeholders in soak_top.v -------------------------------
cur[BD_SZ_UDEC]=4
cur[BD_SZ_UMERGE]=4
cur[BD_SZ_UMUX]=4
cur[BD_SZ_UMEM_USETUP]=8
cur[BD_SZ_UMEM_UCO]=12

write_sizes
echo "baseline (the placeholders):$(show)"
if ! attempt base; then
    echo "the placeholder build does not meet its own constraints -- nothing to"
    echo "tighten from.  See $HIST/tighten_base.log"
    grep VIOLATION "$HIST/tighten_base.log" | head
    exit 1
fi
cp "$HIST/prop_base.vh" "$HIST/prop_last.vh"
echo "baseline routes and passes."
echo

routes=1
sweep=0
while : ; do
    sweep=$((sweep + 1))
    read_prop "$HIST/prop_last.vh"

    changed=0
    for k in "${KEYS[@]}"; do
        want=${prop[$k]}
        [ "$want" -ge "${cur[$k]}" ] && continue      # only ever tighten
        was=${cur[$k]}
        cur[$k]=$want
        write_sizes
        routes=$((routes + 1))
        if attempt "try_${k}_${want}"; then
            cp "$HIST/prop_try_${k}_${want}.vh" "$HIST/prop_last.vh"
            printf "  %-20s %2d -> %-2d  kept\n" "${k#BD_SZ_}" "$was" "$want"
            changed=1
        else
            cur[$k]=$was
            write_sizes
            reason=$(grep -m1 VIOLATION "$HIST/tighten_try_${k}_${want}.log" \
                     | sed 's/^ *//;s/  */ /g')
            printf "  %-20s %2d -> %-2d  REVERTED\n" "${k#BD_SZ_}" "$was" "$want"
            printf "  %-20s          %s\n" "" "${reason:-place-and-route failed}"
        fi
    done

    [ $changed -eq 0 ] && break
    echo "  -- sweep $sweep done:$(show)"
done

write_sizes
./flow.sh > "$HIST/flow_final.log" 2>&1
python3 verify/tighten.py --emit "$HIST/final_prop.vh" > "$HIST/tighten_final.log" 2>&1
final=$?

echo
echo "settled after $sweep sweep(s), $routes place-and-route runs"
echo "verified assignment:$(show)"
echo "written to $SIZEFILE -- pass it back with BD_SIZES=$SIZEFILE ./flow.sh"
if [ $final -ne 0 ]; then
    echo "but the final re-route does not check out -- see $HIST/tighten_final.log"
    exit 1
fi
echo
echo "Every length above was applied, re-routed and re-checked, not "
echo "extrapolated.  It is one build's answer and expires with the build."
