#!/usr/bin/env python3
"""Turn FileCheck `// CHECK:` lines back into plain handshake-dialect text.

This is test scaffolding, not part of the real reader (see parse.py's
docstring). It exists because a large share of the corpus under
dynamatic/test/ is lit tests: the *input* to a pass is often not handshake
at all (arith/cf, converted to handshake by the pass under test), and the
only place the handshake-dialect *output* shows up is autogenerated
`// CHECK:` comments, e.g.:

    // CHECK-LABEL:   handshake.func @foo(
    // CHECK-SAME:                        %[[VAL_0:.*]]: !handshake.control<>, ...) {
    // CHECK:           %[[VAL_1:.*]] = fork [2] %[[VAL_0]] : <>
    // CHECK:           end %[[VAL_1]]#0 : <>
    // CHECK:         }

`utils/generate-test-checks.py` (the tool that writes these) numbers every
SSA value in the pass's output as `%[[VAL_N:.*]]` on first mention and
`%[[VAL_N]]` afterwards, and pads the real source so it lines up in columns.
Undo both: rewrite the VAL placeholders to plain `%N`, and let parse.py's
tokenizer (which treats runs of whitespace as insignificant) absorb the
padding.

Real dynamatic-opt output (bdc/hs/corpus/*.out.mlir) is the authoritative
corpus; this module only recovers a second, larger source of cases from the
lit tests that predate it.
"""

import re

_DIRECTIVE_RE = re.compile(r"^\s*//\s*CHECK(-LABEL|-SAME)?:(.*)$")
_VAL_RE = re.compile(r"%\[\[VAL_(\d+)(?::[^\]]*)?\]\]")
# FileCheck escapes a literal regex metacharacter as `{{\X}}` inside a
# pattern (the corpus only ever needs this for `[`, e.g. `mem_controller
# {{\[}}%0`, but handle the general form defensively).
_LITERAL_ESCAPE_RE = re.compile(r"\{\{\\(.)\}\}")


def _normalize_line(content):
    content = _VAL_RE.sub(lambda m: f"%{m.group(1)}", content)
    content = _LITERAL_ESCAPE_RE.sub(lambda m: m.group(1), content)
    return content


def extract_checks(text):
    """Reconstruct plain handshake text from the `// CHECK...:` lines in
    `text`. CHECK and CHECK-LABEL each start a new line of reconstructed
    text; CHECK-SAME continues the previous one (that is what it means in
    FileCheck: the match picks up on the same logical line, just wrapped for
    readability in the .mlir source). Lines with no CHECK directives at all
    contribute nothing. Returns "" if there is nothing to reconstruct."""
    out_lines = []
    for line in text.splitlines():
        m = _DIRECTIVE_RE.match(line)
        if not m:
            continue
        kind, content = m.group(1), m.group(2)
        content = _normalize_line(content)
        if kind == "-SAME":
            if out_lines:
                out_lines[-1] += " " + content.strip()
            else:
                out_lines.append(content.strip())
        else:
            out_lines.append(content.rstrip())
    return "\n".join(out_lines)


def split_lit_cases(text):
    """Split one lit-test file's text on `// -----` separator lines, as
    `--split-input-file` does. Returns the list of chunks (including the
    first, before any separator)."""
    return re.split(r"^\s*//\s*-----\s*$", text, flags=re.MULTILINE)
